export const AUTH_FETCH_USER = 'AUTH_FETCH_USER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_CONTENT = 'ADD_CONTENT';
export const ADD_CONTENT_START = 'ADD_CONTENT_START';
export const ADD_CONTENT_SUCCESS = 'ADD_CONTENT_SUCCESS';
export const ADD_CONTENT_FAIL = 'ADD_CONTENT_FAIL';

export const FETCH_CONTENTS_START = 'FETCH_CONTENTS_START';
export const FETCH_CONTENTS_SUCCESS = 'FETCH_CONTENTS_SUCCESS';
export const FETCH_CONTENTS_FAIL = 'FETCH_CONTENTS_FAIL';
